version: '3.8'

services:
  crew-schedule-parser:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped 